# Generated by Django 3.2.8 on 2021-10-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_alter_newuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table=None,
        ),
    ]
