# Generated by Django 3.2.8 on 2021-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0006_auto_20211027_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(default='-1', max_length=12, null=True),
        ),
    ]
