# Generated by Django 3.2.8 on 2021-10-27 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello', '0007_alter_phone_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=100)),
                ('new_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=70, unique=True)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='auth_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='phone',
            name='profile_picture',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello.uploads'),
        ),
    ]
