# Generated by Django 3.2.8 on 2021-10-27 13:38

from django.db import migrations, models
import trello.models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0008_auto_20211027_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='auth_user',
        ),
        migrations.AlterField(
            model_name='phone',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=trello.models.getpath),
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
