# Generated by Django 3.2.8 on 2021-10-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello', '0009_auto_20211027_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phone',
            name='user',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
