# Generated by Django 3.2.8 on 2021-10-28 13:04

from django.db import migrations, models
import trello.models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0010_auto_20211027_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=trello.models.getpath),
        ),
    ]
