# Generated by Django 3.2.8 on 2021-11-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0013_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('org', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='trello.org')),
            ],
        ),
    ]
