# Generated by Django 3.2.8 on 2021-11-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0015_auto_20211101_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'org')},
        ),
    ]
