# Generated by Django 3.2.8 on 2021-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0016_auto_20211112_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
