# Generated by Django 3.2.8 on 2021-11-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0017_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
